language: generic 

sudo: required

services:
  - Docker

before_install:
  - docker build -t kkboranbay/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true kkboranbay/docker-react npm run test
  # - docker run kkboranbay/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2" # http://dockerreact-env.eba-jtdppwuc.us-east-2.elasticbeanstalk.com/
  app: "docker-react"
  env: "dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-958428388345"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY